language: node_js
node_js:
  - 'stable'

script:
  - npm test
  - npm start

deploy:
  provider: heroku
  api_key:
    secure: $he
  strategy: git
  app:
    master: lofsystem_dev
  run:
    - restart
